# """
# ******************************************************************************
# settings
# ******************************************************************************
# """

SEED:
  seed: 1

NET_ARCH:
  f_in : 2
  f_out: 1
  f_hid: 20
  depth: 9

PARAM_TRAIN:
  lr: .001
  beta: .99
  tau: 10
