# """
# ******************************************************************************
# settings
# ******************************************************************************
# """

SEED:
  seed: 0

NET_ARCH:
  f_in : 2
  f_out: 1
  f_hid: 128
  depth: 5
